name: 步步宝

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/wishcaiji/JD-scripts.git ~/JD-scripts
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/JD-scripts
          npm install
          npm install cron
          npm install request
      - name: '运行 【步步宝】'
        run: |
          cd ~/Scripts
          node Task/bububao.js
        
